version: '3.8'
services:
  php:
    build: ./php
    image: php
    hostname: php
    container_name: php
    volumes:
      - './vimrc:/etc/vim/vimrc'
      - './bashrc:/root/.bashrc'
    tty: true
    stdin_open: true
  react:
    build: ./react
    image: react
    hostname: react
    container_name: react
    volumes:
      - './vimrc:/etc/vim/vimrc'
      - './bashrc:/root/.bashrc'
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
